---
name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: dapconfig-schema.json
          INPUT_JSONS: samples/valid.json
